// Generated by CoffeeScript 1.3.2
(function() {
  var $, add, help, main, pathFormat, reroute;

  pathFormat = /(?:([0-9]+)(?:\+([0-9]+))?)(?:\:(.*))/;

  $ = window.jQuery;

  add = function() {
    return alert('Adding!');
  };

  help = function() {
    return alert('Here is the help');
  };

  main = function(path) {
    var parse;
    parse = function(path) {
      path = path.match(pathFormat);
      return {
        startDate: new Date(path[1] * 1000),
        description: path[3]
      };
    };
    path = parse(path);
    $('#t').text(path.startDate.toLocaleString());
    return $('#d').text(path.description);
  };

  reroute = function() {
    var path;
    path = window.location.hash;
    switch (true) {
      case path === '?':
        return help();
      case pathFormat.test(path):
        return main(path);
      default:
        return add();
    }
  };

  window.onhashchange = reroute;

  $(function() {
    return reroute();
  });

}).call(this);
